name: "Zenn: Create new article (yml)"
description: "Automatically create a new article file when an issue is created."
title: "title: "
labels: ["zenn:new-article"]
body:
  - type: dropdown
    id: type
    attributes:
      label: "Type (Zenn)"
      options: [tech, idea]
      default: 0
  - type: input
    id: emoji
    attributes:
      label: "Emoji (If empty, 📝)"
      placeholder: "📝"
  - type: input
    id: topics
    attributes:
      label: "Topics (Comma separated)"
      placeholder: "bigquery, dbt"
  - type: textarea
    id: memo
    attributes:
      label: "Memo (Optional・Markdown)"
      placeholder: |
        メモ:1行目だけ拾う（複数行は1行目まで）
